import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {readFile} from 'node:fs/promises';
test('apply keeps form, submits once same-origin then TEST SDK; cancel/reload consult server not client PAID',async t=>{
 const server=createServer(async(req,res)=>{try{const p=req.url.split('?')[0],file=p.startsWith('/src/')?'..'+p:'../index.html';res.writeHead(200,{'Content-Type':p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html'});res.end(await readFile(new URL(file,import.meta.url)));}catch{res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();return new Promise(r=>server.close(r));});
 const {chromium}=await import('/Users/choi/.hermes/hermes-agent/node_modules/playwright/index.mjs');const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});t.after(()=>browser.close());const page=await browser.newPage();const base=`http://127.0.0.1:${server.address().port}`;let submitted=0,opened=0,verified=0,exists=false,paid=false;const receipt='a0000000-0000-4000-8000-000000000001';
 await page.route('**/*',async r=>{const u=r.request().url();if(u==='https://cdn.portone.io/v2/browser-sdk.js')return r.fulfill({contentType:'text/javascript',body:"window.calls=[];window.PortOne={requestPayment:async p=>{window.calls.push(p);return {code:'FAILURE_TYPE_STOPPED',message:'PRIVATE'};}}"});if(u.includes('/api/test/apply/')){assert.equal(r.request().method(),'POST');assert.equal(new URL(u).search,'');const b=r.request().postDataJSON();if(u.endsWith('/session'))return r.fulfill({json:{status:'session-ready'}});if(u.endsWith('/submit')){submitted++;assert.equal(b.brief,'합성 TEST 안내');assert.equal(b.plan,'Standard');assert.equal(b.totalAmount,undefined);exists=true;return r.fulfill({json:{receipt,status:'pending-review'}});}if(u.endsWith('/open')){opened++;assert.deepEqual(b,{consentVersion:'cjy-test-2026-09-26',granted:true});return r.fulfill({json:{receipt,status:'checkout-ready',customer:{fullName:'TEST',phoneNumber:'01000000000'},orderId:'order-server',paymentId:'cjy-server',storeId:'store-test',channelKey:'channel-test',orderName:'CJY Reels Standard',totalAmount:273900,currency:'KRW',payMethod:'CARD',state:'pending_payment',environment:'test'}});}if(u.endsWith('/verify')){verified++;paid=true;}return r.fulfill({json:exists?{receipt,status:'order-existing',state:paid?'pilot_pending':'pending_payment',environment:'test'}:{status:'session-ready'}});}if(u.startsWith(base))return r.continue();return r.abort();});
 await page.goto(base+'/apply');await page.waitForFunction(()=>!document.querySelector('button[type=submit]').disabled);
 await page.locator('[name=customerName]').fill('TEST');await page.locator('[name=customerPhone]').fill('01000000000');await page.locator('[name=brief]').fill('합성 TEST 안내');for(const name of ['termsConsent','refundConsent','processingConsent','postingConsent','privacyConsent','noticeConsent'])await page.locator(`[name=${name}]`).check();
 assert.equal(await page.locator('[name=testConsent]').count(),1);assert.equal(await page.locator('[name=testEmail]').count(),1);assert.ok((await page.locator('[name=testEmail]').boundingBox()).width>=200);
 await page.locator('[name=testConsent]').check();await page.locator('[name=testEmail]').fill('test@example.invalid');await page.locator('button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#checkout-status').textContent.includes('서버 결제 확인 완료'));
 assert.equal(submitted,1);assert.equal(opened,1);assert.equal(verified,1);const calls=await page.evaluate(()=>window.calls);assert.equal(calls.length,1);assert.equal(calls[0].currency,'CURRENCY_KRW');assert.deepEqual(calls[0].customer,{fullName:'TEST',phoneNumber:'01000000000',email:'test@example.invalid'});assert.equal(calls[0].totalAmount,273900);assert.equal(calls[0].redirectUrl,base+'/apply');assert.doesNotMatch(await page.locator('body').textContent(),/PRIVATE/);
 await page.reload();await page.waitForFunction(()=>document.querySelector('#checkout-status').textContent.includes('서버 결제 확인 완료'));assert.equal(submitted,1);assert.equal(opened,1);assert.equal(await page.locator('button[type=submit]').isDisabled(),true);
 assert.equal(await page.evaluate(()=>localStorage.length),0);assert.equal(await page.evaluate(()=>Object.values(sessionStorage).some(x=>x.includes('합성 TEST'))),false);
});

test('SDK pre-open failure permits explicit retry; lost open response and invoked payment never reopen',async t=>{
 const {chromium}=await import('/Users/choi/.hermes/hermes-agent/node_modules/playwright/index.mjs');const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});t.after(()=>browser.close());
 for(const lostOpen of [false,true]){
 const page=await browser.newPage();let opens=0,loads=0;const receipt='a0000000-0000-4000-8000-000000000003';
 await page.route('**/*',async route=>{const u=new URL(route.request().url());
 if(u.href==='https://cdn.portone.io/v2/browser-sdk.js'){loads++;if(loads===1)return route.abort();return route.fulfill({contentType:'text/javascript',body:"window.calls=0;window.PortOne={requestPayment:async()=>{window.calls++;throw Error('unknown after invocation');}};"});}
 if(u.pathname.startsWith('/api/test/apply/')){if(u.pathname.endsWith('/session'))return route.fulfill({json:{status:'session-ready'}});if(u.pathname.endsWith('/open')){opens++;if(lostOpen)return route.abort();return route.fulfill({json:{receipt,status:'checkout-ready',orderId:'owned',paymentId:'owned-payment',environment:'test',state:'pending_payment',totalAmount:273900,currency:'KRW',customer:{fullName:'TEST',phoneNumber:'01000000000'}}});}return route.fulfill({json:{receipt,status:opens?'order-existing':'pending-review',...(opens?{orderId:'owned',state:'pending_payment',environment:'test'}:{})}});}
 if(u.origin!=='https://cjy.app')return route.abort();const path=u.pathname.startsWith('/src/')?u.pathname:'/index.html';return route.fulfill({contentType:path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'text/html',body:await readFile(new URL('..'+path,import.meta.url))});});
 await page.goto('https://cjy.app/apply');await page.waitForFunction(()=>!document.querySelector('[data-test-controls]').hidden);await page.locator('[name=testConsent]').check();await page.locator('[name=testEmail]').fill('test@example.invalid');await page.locator('[data-test-pay]').click();await page.waitForFunction(()=>document.querySelector('#checkout-status').textContent.includes('결과 미확인'));
 assert.equal(opens,0);assert.equal(loads,1);assert.equal(await page.locator('[data-test-pay]').isDisabled(),false);
 await page.locator('[data-test-pay]').click();await page.waitForFunction(()=>document.querySelector('[data-test-pay]').disabled);await page.waitForFunction(()=>document.querySelector('#checkout-status').textContent.includes('결과 미확인'));
 assert.equal(opens,1);assert.equal(loads,2);assert.equal(await page.locator('[data-test-pay]').isDisabled(),true);assert.equal(await page.evaluate(()=>window.calls),lostOpen?0:1);
 await page.locator('[data-test-check]').click();await page.reload();await page.waitForFunction(()=>document.querySelector('#checkout-status').textContent.includes('서버 결제 확인 대기'));assert.equal(opens,1);assert.equal(await page.locator('[data-test-pay]').isDisabled(),true);await page.close();
 }
});

test('pending approval, back/redirect and network recovery never resubmit or reopen payment automatically',async t=>{
 const {chromium}=await import('/Users/choi/.hermes/hermes-agent/node_modules/playwright/index.mjs');const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:390,height:844}});const origin='https://cjy.app';let opens=0,submits=0;
 const receipt='a0000000-0000-4000-8000-000000000002';let phase='pending-review',offline=false;
 await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.pathname.startsWith('/api/test/apply/')){if(offline)return route.abort();if(u.pathname.endsWith('/submit'))submits++;if(u.pathname.endsWith('/open'))opens++;return route.fulfill({json:u.pathname.endsWith('/session')?{status:'session-ready'}:{receipt,status:phase,...(phase==='order-existing'?{orderId:'same-order',state:'pending_payment',environment:'test'}:{})}});}if(u.origin!==origin)return route.abort();if(u.pathname.startsWith('/src/')){return route.fulfill({contentType:u.pathname.endsWith('.js')?'text/javascript':'text/css',body:await readFile(new URL('..'+u.pathname,import.meta.url))});}return route.fulfill({contentType:'text/html',body:await readFile(new URL('../index.html',import.meta.url))});});
 await page.goto(origin+'/apply');await page.waitForFunction(()=>document.querySelector('#checkout-status').textContent.includes('검토 대기'));assert.equal(await page.locator('button[type=submit]').isDisabled(),true);assert.equal(opens,0);assert.equal(submits,0);
 phase='order-existing';await page.goto(origin+'/apply?paymentId=untrusted&code=PAID');await page.waitForFunction(()=>document.querySelector('#checkout-status').textContent.includes('서버 결제 확인 대기'));assert.equal(page.url(),origin+'/apply');assert.equal(opens,0);assert.equal(submits,0);assert.equal(await page.locator('[data-test-pay]').isDisabled(),true);
 offline=true;await page.locator('[data-test-check]').click();await page.waitForFunction(()=>document.querySelector('#checkout-status').textContent.includes('결과 미확인'));offline=false;await page.locator('[data-test-check]').click();await page.waitForFunction(()=>document.querySelector('#checkout-status').textContent.includes('서버 결제 확인 대기'));assert.equal(submits,0);assert.equal(opens,0);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
});
