import test from 'node:test';import assert from 'node:assert/strict';import {directPage,receipt,readyOrder} from './fixtures/direct-browser.mjs';
const draftId='a0000000-0000-4000-8000-000000000011',childId='a0000000-0000-4000-8000-000000000012';
const application={customerName:'TEST',customerPhone:'01000000000',service:'reels',plan:'Standard',autoPost:'yes',existingAccount:'no',brief:'Synthetic request',channel:'telegram'};
for(const mode of ['lost-open','invoked-unknown','cancel'])test(`SDK load retry then ${mode} preserves form and never navigates Order without server PAID`,async t=>{
 let loads=0,saves=0,opens=0,payments=0;const order={...readyOrder,draftId,plan:'Standard'};
 const {page,fill}=await directPage(t,async(a,r)=>{let json;if(a==='submit'){saves++;json={receipt,status:'pending-review',draftId};}if(a==='open'){opens++;if(mode==='lost-open'){await r.abort();return true;}json=order;}if(a==='status')json={status:'session-ready',draftId};if(a==='verify')json={...order,status:'order-existing'};if(a==='retry-edit')json={receipt,status:'pending-review',draftId:childId,application,editable:true,retryOriginal:{draftId,application}};if(json){await r.fulfill({json});return true;}},{sdk:async r=>{loads++;if(loads===1)return r.abort();return r.fulfill({contentType:'text/javascript',body:`window.PortOne={requestPayment:async()=>{await window.recordPayment();${mode==='invoked-unknown'?"throw Error('unknown')":"return {code:'FAILURE_TYPE_STOPPED'}"};}};`});}});
 await page.exposeFunction('recordPayment',()=>payments++);await fill();await page.locator('[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#checkout-status').textContent.includes('준비에 실패'));assert.equal(saves,0);assert.equal(opens,0);
 await page.locator('[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('[type=submit]').disabled);assert.match(page.url(),/\/apply/);assert.equal(await page.locator('[name=brief]').inputValue(),'Synthetic request');assert.equal(saves,1);assert.equal(opens,1);assert.equal(loads,2);assert.equal(payments,mode==='lost-open'?0:1);
 assert.match(await page.locator('#checkout-status').textContent(),mode==='cancel'?/닫았습니다/:/확인 중/);
});
test('untrusted callback URL cannot assert PAID, navigate Order, or open a provider window',async t=>{
 let opens=0,submits=0;const {page}=await directPage(t,async(a,r)=>{if(a==='open')opens++;if(a==='submit')submits++;if(a==='status'){await r.fulfill({json:{status:'session-ready',draftId}});return true;}},{query:'?paymentId=untrusted&code=PAID'});
 await page.waitForFunction(()=>!document.querySelector('[type=submit]').disabled);assert.match(page.url(),/\/apply/);assert.equal(opens,0);assert.equal(submits,0);assert.equal(await page.locator('[data-existing-order]').isVisible(),false);
});
