import test from 'node:test';import assert from 'node:assert/strict';import {directPage,receipt,readyOrder} from './fixtures/direct-browser.mjs';
for(const mode of ['lost-open','invoked-unknown','cancel'])test(`SDK known failure retry then ${mode} recovers only on /order, never creates another payment`,async t=>{
 let loads=0,saves=0,opens=0,verifies=0,payments=0;const draftId='a0000000-0000-4000-8000-000000000011';const order={...readyOrder,draftId,plan:'Standard'};
 const {page,fill}=await directPage(t,async(a,r)=>{if(a==='submit'){saves++;await r.fulfill({json:{receipt,status:'pending-review',draftId}});return true;}if(a==='open'){opens++;if(mode==='lost-open')await r.abort();else await r.fulfill({json:order});return true;}if(a==='verify')verifies++;if(a==='status'||a==='verify'){await r.fulfill({json:opens?{...order,status:'order-existing'}:{status:'session-ready',draftId}});return true;}if(a==='orders'){await r.fulfill({json:{orders:opens?[order]:[],draftId}});return true;}},{sdk:async r=>{loads++;if(loads===1)return r.abort();return r.fulfill({contentType:'text/javascript',body:`window.PortOne={requestPayment:async()=>{await window.recordPayment();${mode==='invoked-unknown'?"throw Error('unknown')":"return {code:'FAILURE_TYPE_STOPPED'}"};}};`});}});
 await page.exposeFunction('recordPayment',()=>payments++);await fill();await page.locator('[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#checkout-status').textContent.includes('준비에 실패'));assert.equal(saves,0);assert.equal(opens,0);assert.equal(await page.locator('[type=submit]').isDisabled(),false);
 await page.locator('[type=submit]').click();await page.waitForURL('https://cjy.app/order');await page.waitForFunction(()=>document.querySelector('[data-order-list]').textContent.includes('결제 확인 중'));assert.equal(saves,1);assert.equal(opens,1);assert.equal(loads,2);assert.equal(payments,mode==='lost-open'?0:1);assert.equal(await page.locator('[data-direct-checkout] [type=submit],[data-monthly-renew] [type=submit]').count(),0);assert.equal(await page.locator('[data-monthly-recover] [type=submit]').count(),1);
 await page.locator('[data-order-refresh]').click();await page.reload();await page.waitForFunction(()=>document.querySelector('[data-order-list]').textContent.includes('결제 확인 중'));assert.equal(opens,1);assert.equal(saves,1);assert.ok(verifies>=1);
});
test('old client PAID callback, network unknown and reload display only server-owned status',async t=>{
 let opens=0,submits=0,offline=false;const order={...readyOrder,plan:'Premium',draftId:'a0000000-0000-4000-8000-000000000011',totalAmount:1208900};
 const {page}=await directPage(t,async(a,r)=>{if(a==='open')opens++;if(a==='submit')submits++;if(a==='orders'){if(offline)await r.abort();else await r.fulfill({json:{orders:[order],draftId:order.draftId}});return true;}if(a==='verify'){await r.fulfill({json:order});return true;}},{query:'?paymentId=untrusted&code=PAID'});
 await page.waitForFunction(()=>document.querySelector('[data-order-list]')?.textContent.includes('결제 확인 중'));assert.equal(page.url(),'https://cjy.app/order');assert.match(await page.locator('[data-order-list]').textContent(),/1,208,900/);offline=true;await page.locator('[data-order-refresh]').click();await page.waitForFunction(()=>document.querySelector('[data-order-message]').textContent.includes('지연'));offline=false;await page.locator('[data-order-refresh]').click();await page.reload();await page.waitForFunction(()=>document.querySelector('[data-order-list]').textContent.includes('결제 확인 중'));assert.equal(opens,0);assert.equal(submits,0);
});
