import test from 'node:test';import assert from 'node:assert/strict';import {directPage,receipt,readyOrder} from './fixtures/direct-browser.mjs';
test('invalid fields and unchecked terms/refund or privacy never save; exact totals and mobile layout',async t=>{
 let saves=0;const {page,fill}=await directPage(t,async(a,r)=>{if(a==='submit'){saves++;await r.fulfill({json:{receipt,status:'pending-review'}});return true;}if(a==='open'){await r.fulfill({json:readyOrder});return true;}if(a==='verify'){await r.fulfill({json:{...readyOrder,status:'order-existing'}});return true;}},{viewport:{width:320,height:740}});
 await page.waitForFunction(()=>!document.querySelector('[type=submit]').disabled);const totals={Standard:'273,900',Deluxe:'768,900',Premium:'1,208,900'};for(const [p,total] of Object.entries(totals)){await page.locator('[name=plan]').selectOption(p);assert.match(await page.locator('#order-total').textContent(),new RegExp(total));}
 await fill();await page.locator('[name=customerPhone]').fill('abc');await page.locator('[type=submit]').click();assert.equal(saves,0);await page.locator('[name=customerPhone]').fill('01000000000');for(const n of ['termsConsent','privacyConsent']){await page.locator(`[name=${n}]`).uncheck();await page.locator('[type=submit]').click();assert.equal(saves,0);await page.locator(`[name=${n}]`).check();}
 assert.equal(await page.locator('input[type=checkbox]').count(),2);assert.equal(await page.locator('[name=processingConsent],[name=postingConsent],[name=noticeConsent]').count(),0);for(const href of ['/terms','/refund','/privacy'])assert.equal(await page.locator(`.consents a[href="${href}"]`).count(),1);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.locator('[name=testEmail]').getAttribute('required'),'');assert.equal(await page.evaluate(()=>localStorage.length),0);
});
test('invalid successful intake response never opens PG or inserts markup; unknown save stays held',async t=>{
 let opens=0;const {page,fill}=await directPage(t,async(a,r)=>{if(a==='submit'){await r.fulfill({json:{receipt:'<img src=x>',status:'registered'}});return true;}if(a==='open'){opens++;await r.fulfill({json:readyOrder});return true;}});await fill();await page.locator('[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#checkout-status').textContent.includes('결과 미확인'));assert.equal(opens,0);assert.equal(await page.locator('#checkout-status img').count(),0);assert.equal(await page.locator('[type=submit]').isDisabled(),true);
});
test('known intake rejection permits explicit retry without leaking raw errors',async t=>{
 let code=400,saves=0;const {page,fill}=await directPage(t,async(a,r)=>{if(a==='submit'){saves++;await r.fulfill({status:code,json:{error:'PRIVATE'}});return true;}});await fill();for(code of [400,409,429]){await page.locator('[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('[type=submit]').disabled&&document.querySelector('#checkout-status').textContent.includes('입력'));}assert.equal(saves,3);assert.doesNotMatch(await page.locator('#checkout-status').textContent(),/PRIVATE/);
});
