import test from 'node:test';import assert from 'node:assert/strict';import {directPage,receipt,readyOrder} from './fixtures/direct-browser.mjs';
const draftId='a0000000-0000-4000-8000-000000000011',windowId='a0000000-0000-4000-8000-000000000013',childId='a0000000-0000-4000-8000-000000000012';
const application={customerName:'TEST',customerPhone:'01000000000',service:'reels',plan:'Standard',autoPost:'yes',existingAccount:'no',brief:'Synthetic request',channel:'telegram'};
for(const redirect of [false,true])test(`${redirect?'redirect cancel reload':'SDK cancel'} immediately edits and enables save/pay without waiting for retry/provider`,async t=>{
 const calls=[];const order={...readyOrder,draftId,windowId,application,editable:false};let saved;
 const {page,fill}=await directPage(t,async(a,r)=>{calls.push(a);let json;if(a==='status')json=redirect?order:{status:'session-ready',draftId};if(a==='application')json=order;if(a==='submit')json={receipt,status:'pending-review',draftId};if(a==='open')json=order;if(a==='retry-edit'){await new Promise(resolve=>setTimeout(resolve,1000));json={receipt,status:'pending-review',draftId:childId,application,editable:true,retryOriginal:{draftId,application}};}if(a==='save'){saved=r.request().postDataJSON();json={receipt,status:'pending-review',draftId:childId,application:{...application,brief:saved.brief},editable:true};}if(json){await r.fulfill({json});return true;}},{query:redirect?`?draftId=${draftId}&windowId=${windowId}&code=FAILURE_TYPE_STOPPED`:''});
 if(!redirect){await fill();await page.locator('[type=submit]').click();}
 await page.waitForTimeout(150);assert.equal(await page.locator('[type=submit]').isEnabled(),true,'pay immediately enabled');assert.equal(await page.locator('[data-save-application]').isEnabled(),true);assert.equal(await page.locator('[name=brief]').isEnabled(),true);assert.equal(calls.includes('retry-edit'),false,'no status gate on return');assert.doesNotMatch(await page.locator('#checkout-status').textContent(),/확인 중|점검|준비 중/);assert.match(page.url(),/\/apply/);
 await page.locator('[name=brief]').fill('Edited immediately');await page.locator('[name=draftPrivacyConsent]').check();await page.locator('[data-save-application]').click();await page.waitForFunction(()=>document.querySelector('#checkout-status').textContent.includes('접수를 저장'));assert.equal(saved.draftId,childId);assert.equal(saved.brief,'Edited immediately');
});
