import test from 'node:test';import assert from 'node:assert/strict';import {directPage,readyOrder} from './fixtures/direct-browser.mjs';
const orderId='a0000000-0000-4000-8000-000000000001',draftId='b0000000-0000-4000-8000-000000000001';
for(const width of [390,1440])test(`paid contact issue display safe ephemeral code, confirm without new nonce and connected no code ${width}`,async t=>{
 let state='available',issued=0;const code='link_'+'x'.repeat(43),expiresAt=new Date(Date.now()+600000).toISOString();const {page}=await directPage(t,async(a,r)=>{if(a==='orders'){await r.fulfill({json:{draftId,orders:[{...readyOrder,state:'paid',orderId,draftId,contact:{status:state,expiresAt}}]}});return true;}if(a==='contact-link'){issued++;assert.deepEqual(r.request().postDataJSON(),{orderId});state='waiting';await r.fulfill({json:{status:'waiting',code,expiresAt,deepLink:'https://t.me/cjysolutionbot?start='+code}});return true;}},{viewport:{width,height:1000}});
 await page.goto('https://cjy.app/order');await page.locator('[data-contact-issue]').click();await page.waitForSelector('[data-contact-code]');assert.equal(await page.locator('[data-contact-code]').textContent(),'/start '+code);assert.equal(await page.locator('[data-contact-link]').getAttribute('href'),'https://t.me/cjysolutionbot?start='+code);assert.equal(issued,1);
 await page.locator('[data-contact-confirm]').click();assert.equal(issued,1);state='connected';await page.locator('[data-contact-confirm]').click();await page.waitForFunction(()=>document.querySelector('[data-telegram-connection]').textContent.includes('연결 완료'));assert.equal(await page.locator('[data-contact-code]').count(),0);assert.equal(await page.locator('[data-contact-issue]').count(),0);assert.equal(issued,1);
 await page.screenshot({path:`/Users/choi/.hermes/cache/cjy-contact-connected-${width}.png`,fullPage:true});
});
test('expired code explicit regenerate; lost-response waiting never silently regenerates',async t=>{
 let calls=[];const {page}=await directPage(t,async(a,r)=>{calls.push(a);if(a==='orders'){await r.fulfill({json:{draftId,orders:[{...readyOrder,state:'paid',orderId,draftId,contact:{status:'expired',expiresAt:'2026-01-01T00:00:00Z'}}]}});return true;}if(a==='contact-link'){assert.deepEqual(r.request().postDataJSON(),{orderId,regenerate:true});await r.fulfill({status:503,json:{}});return true;}});
 await page.goto('https://cjy.app/order');await page.locator('[data-contact-regenerate]').click();await page.waitForFunction(()=>document.querySelector('[data-order-message]').textContent.includes('확인'));assert.equal(calls.filter(a=>a==='contact-link').length,1);
});
