import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
test('two explicit consents and one 결제하기 action preload SDK then save order and pay all catalog plans',async t=>{
 const {chromium}=await import('/Users/choi/.hermes/hermes-agent/node_modules/playwright/index.mjs');const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});t.after(()=>browser.close());
 for(const [plan,total] of [['Standard',273900],['Deluxe',768900],['Premium',1208900]]){
 const page=await browser.newPage({viewport:{width:390,height:844}});let submitted=false,opened=false;const trace=[];const receipt='a0000000-0000-4000-8000-000000000001';
 await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.href==='https://cdn.portone.io/v2/browser-sdk.js'){trace.push('sdk');return route.fulfill({contentType:'text/javascript',body:"window.calls=[];window.PortOne={requestPayment:async p=>{window.calls.push(p);return {};}}"});}if(u.pathname.startsWith('/api/test/apply/')){const action=u.pathname.split('/').at(-1);if(action==='session')return route.fulfill({json:{status:'session-ready'}});if(action==='submit'){trace.push('submit');const b=route.request().postDataJSON();assert.deepEqual(b.consentBundle,{version:'cjy-direct-test-2026-09-27',termsRefund:true,privacy:true});assert.equal(b.plan,plan);assert.equal(b.processingConsent,undefined);submitted=true;return route.fulfill({json:{receipt,status:'pending-review'}});}if(action==='open'){trace.push('open');opened=true;return route.fulfill({json:{receipt,orderId:'owned',status:'checkout-ready',environment:'test',state:'pending_payment',storeId:'store-test',channelKey:'channel-test',paymentId:'owned',orderName:'CJY Reels '+plan,totalAmount:total,currency:'KRW',payMethod:'CARD',customer:{fullName:'TEST',phoneNumber:'01000000000'}}});}return route.fulfill({json:opened?{receipt,orderId:'owned',status:'order-existing',environment:'test',state:'paid',production:'awaiting-review'}:submitted?{receipt,status:'pending-review'}:{status:'session-ready'}});}if(u.origin!=='https://cjy.app')return route.abort();const p=u.pathname.startsWith('/src/')?u.pathname:'/index.html';return route.fulfill({contentType:p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html',body:await readFile(new URL('..'+p,import.meta.url))});});
 await page.goto('https://cjy.app/apply?plan='+plan);await page.waitForFunction(()=>!document.querySelector('button[type=submit]').disabled);assert.equal(await page.locator('button[type=submit]').textContent(),'결제하기');assert.equal(await page.locator('input[type=checkbox]').count(),2);
 for(const [name,value] of Object.entries({customerName:'TEST',customerPhone:'01000000000',brief:'합성 TEST 안내',testEmail:'test@example.invalid'}))await page.locator(`[name=${name}]`).fill(value);for(const name of ['termsConsent','privacyConsent'])await page.locator(`[name=${name}]`).check();await page.locator('button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#checkout-status').textContent.includes('결제 완료'));
 assert.deepEqual(trace,['sdk','submit','open']);const calls=await page.evaluate(()=>window.calls);assert.equal(calls.length,1);assert.equal(calls[0].totalAmount,total);assert.equal(calls[0].currency,'CURRENCY_KRW');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.doesNotMatch(await page.locator('#checkout-status').textContent(),/제작 시작|전달 대기/);await page.reload();await page.waitForFunction(()=>document.querySelector('#checkout-status').textContent.includes('결제 완료'));assert.deepEqual(trace,['sdk','submit','open']);await page.close();
 }
});
