import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {readFile} from 'node:fs/promises';
for (const submit of ['click','Enter']) test(`public checkout ${submit} sends only consent; SDK uses server identity; cancellation reconciles PAID and reload cannot duplicate`,async t=>{
 const server=createServer(async(req,res)=>{try{const p=req.url.split('?')[0];const file=p.startsWith('/src/')?'..'+p:'../public/test/checkout/index.html';const bytes=await readFile(new URL(file,import.meta.url));res.writeHead(200,{'Content-Type':p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html'});res.end(bytes);}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();return new Promise(r=>server.close(r));});
 const {chromium}=await import('/Users/choi/.hermes/hermes-agent/node_modules/playwright/index.mjs');const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:390,height:844}});const base=`http://127.0.0.1:${server.address().port}`;let opens=0,verifies=0,external=0;
 await page.route('**/*',async route=>{const u=route.request().url();if(u==='https://cdn.portone.io/v2/browser-sdk.js')return route.fulfill({contentType:'text/javascript',body:"window.calls=[];window.PortOne={requestPayment:async options=>{window.calls.push(options);return {code:'FAILURE_TYPE_STOPPED',pgCode:'USER_CANCEL',message:'PRIVATE'};}}"});if(u.includes('/api/test/checkout/')){const body=route.request().postDataJSON();if(u.endsWith('/open')){opens++;assert.deepEqual(body,{consentVersion:'cjy-test-2026-09-26',granted:true});return route.fulfill({json:{orderId:'order-server',paymentId:'cjy-server',storeId:'store-test',channelKey:'channel-test',orderName:'CJY Reels Standard',totalAmount:273900,currency:'KRW',payMethod:'CARD',state:'pending_payment',environment:'test'}});}if(u.endsWith('/verify'))verifies++;return route.fulfill({json:{state:'pilot_pending',orderId:'order-server',initialPilotId:'pilot-server',environment:'test',dispatch:false}});}if(u.startsWith(base))return route.continue();external++;return route.abort();});
 await page.goto(base+'/test/checkout');await page.locator('[name=capability]').fill('x'.repeat(48));await page.locator('[name=fullName]').fill('TEST');await page.locator('[name=phoneNumber]').fill('01000000000');await page.locator('[name=email]').fill('test@example.invalid');await page.locator('[name=consent]').check();if(submit==='Enter')await page.locator('[name=email]').press('Enter');else await page.locator('button[type=submit]').click();
 await page.waitForFunction(()=>document.querySelector('#checkout-status').textContent.includes('사전 승인된 첫 시안 1건'));
 assert.equal(opens,1);assert.equal(verifies,1);assert.equal(external,0);const calls=await page.evaluate(()=>window.calls);assert.equal(calls.length,1);assert.equal(calls[0].paymentId,'cjy-server');assert.equal(calls[0].totalAmount,273900);assert.equal(calls[0].currency,'CURRENCY_KRW');assert.doesNotMatch(await page.locator('body').textContent(),/PRIVATE/);
 await page.reload();await page.waitForFunction(()=>document.querySelector('#checkout-status').textContent.includes('사전 승인된 첫 시안 1건'));assert.equal(await page.locator('button[type=submit]').isDisabled(),true);assert.equal(opens,1);assert.equal(verifies,1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
});
